### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by kihwal** [marrold/AMBEServer#2]
It looks like the baud rate of 460800 is not supported on Macs. termios.h does not define B460800. But when I hard-coded the number in place of the macro, I was able to build and cfsetspeed() did not complain. 460800 does not work with a DV3K even on Linux, so I am unable to verify it works with, say ThumbDV, on OS X.  I am not sure whether there is any macro we can use to detect OS X env to take care of the missing B460800 definition.

In any case, I am happy to report that AMBEServer is working with the DV3K from Internet Labs.  I was able to run Buster on OS X utilizing an AMBE server running locally.

**Comment by kihwal** [comment]
We can do a "uname -s" check in Makefile. But not sure what that does in the Cygwin env, which seems to be supported in the original AMBEServer.

**Comment by marrold** [comment]
Hi Kihwal, 

Thanks for your PR, it's been merged - https://github.com/marrold/AMBEServer/pull/3

**Comment by kihwal** [comment]
Thanks and 73.
